# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Node.js CI

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18.x, 20.x, 22.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v4
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v4
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm instal -g @angular/cli
#     - run: npm i
#     - run: ng build ngx-trade-partner-form


# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Hello world workflow

on:
  push: 
    branches: ["master"]
  pull_request: 
    branches: ["master"]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            token: ${{ secrets.COMMIT_TOKEN }} # Use GitHub Actions token
      - name: Publish Trade Partner Form
        run: |
          npm i -g @angular/cli
          npm i
      - name: Build Trade Partner Form
        run: ng build ngx-trade-partner-form
      - name: Publish Library
        run: |
          git config --global user.name "certaworksit"
          git config --global user.email "cwsithelpdesk@gmail.com"
          git config set advice.addIgnoredFile false
          git add dist/ngx-trade-partner-form/**
          git commit -m "Automated build: Trade Partner Form"
          git branch -m master
          git remote add origin https://github.com/certaworksit/npx-trade-partner.git
          git push origin master
